import { type ResearchSource } from '@/shared/types/research';

const STYLES = `
  :root { color-scheme: dark; }
  body {
    margin: 0;
    background: #0f1115;
    color: #e6e8ee;
    font: 15px/1.6 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  }
  main { max-width: 760px; margin: 0 auto; padding: 56px 24px 96px; }
  header { border-bottom: 1px solid #252a34; padding-bottom: 20px; margin-bottom: 32px; }
  header h1 { margin: 0 0 6px; font-size: 28px; }
  header .meta { color: #8a93a3; font-size: 13px; }
  h2 { font-size: 18px; margin: 36px 0 14px; color: #c9cfdb; }
  section.overview { background: #171a21; border: 1px solid #252a34; border-radius: 8px; padding: 16px 18px; }
  section.conclusion p { margin: 0 0 14px; }
  section.sources article { padding: 18px 0; border-top: 1px solid #252a34; }
  section.sources article h3 { margin: 0 0 6px; font-size: 16px; }
  section.sources article h3 a { color: #5b8cff; text-decoration: none; }
  section.sources article h3 a:hover { text-decoration: underline; }
  section.sources article .status { color: #8a93a3; font-size: 12px; margin: 0 0 10px; text-transform: uppercase; letter-spacing: 0.04em; }
  section.sources article ul { margin: 0; padding-left: 20px; }
  section.sources article li { margin: 4px 0; }
  section.sources article .error { color: #f5a3a3; }
`;

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function summaryToList(summary: string): string {
  const lines = summary
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => line.replace(/^[-*•]\s*/, ''));
  if (lines.length === 0) return '';
  return `<ul>${lines.map((line) => `<li>${escapeHtml(line)}</li>`).join('')}</ul>`;
}

function paragraphs(text: string): string {
  return text
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean)
    .map((block) => `<p>${escapeHtml(block).replace(/\n/g, '<br>')}</p>`)
    .join('');
}

function renderSource(source: ResearchSource): string {
  const heading = `<h3><a href="${escapeHtml(source.url)}" target="_blank" rel="noopener">${escapeHtml(source.title || source.url)}</a></h3>`;
  const status = `<p class="status">${escapeHtml(source.status)}</p>`;
  let body = '';
  if (source.status === 'done' && source.summary) body = summaryToList(source.summary);
  if (source.status === 'error' && source.error) body = `<p class="error">${escapeHtml(source.error)}</p>`;
  return `<article>${heading}${status}${body}</article>`;
}

export interface ReportArgs {
  topic: string;
  createdAt: number;
  sources: ResearchSource[];
  conclusion: string;
  aiOverview?: string;
}

export function buildReportHtml({ topic, createdAt, sources, conclusion, aiOverview }: ReportArgs): string {
  const overview = aiOverview
    ? `<section class="overview"><h2>Google AI overview</h2>${paragraphs(aiOverview)}</section>`
    : '';

  const sourceList = sources.length
    ? `<section class="sources"><h2>Sources</h2>${sources.map(renderSource).join('')}</section>`
    : '';

  const conclusionSection = conclusion
    ? `<section class="conclusion"><h2>Synthesis</h2>${paragraphs(conclusion)}</section>`
    : '';

  return [
    '<!doctype html>',
    '<html lang="en"><head>',
    '<meta charset="utf-8">',
    `<title>Research: ${escapeHtml(topic)}</title>`,
    `<style>${STYLES}</style>`,
    '</head><body><main>',
    `<header><h1>${escapeHtml(topic)}</h1><div class="meta">${new Date(createdAt).toLocaleString()} · Generated by Enclave</div></header>`,
    overview,
    conclusionSection,
    sourceList,
    '</main></body></html>',
  ].join('');
}
